---
- name: Deploy webapp
  hosts: webservers
  become: true
  remote_user: ansible
  gather_facts: yes
  roles:
    -role: webapp
    
- name: Deploy docker
  hosts: webservers
  become: true
  remote_user: ansible
  gather_facts: yes
  roles:
    - role: docker

- name: Deploy apache
  hosts: webservers
  become: true
  remote_user: ansible
  gather_facts: yes
  roles:
    - role: apache

