---
- name: Deploy webapp
  hosts: webservers
  become: true
  remote_user: ansible
  gather_facts: yes
  roles:
    - role: webapp
    
- name: Deploy docker compose cluster
  hosts: webservers
  become: true
  remote_user: ansible
  gather_facts: yes
  roles:
    - role: docker

- name: Start the service
  hosts: webservers
  become: true
  remote_user: ansible
  gather_facts: yes
  roles:
    - role: startup