- name: Copy docker-compose.yml to server
  copy:
    src: docker-compose.yml
    dest: /home/ansible/

- name: Create Apache Docker folders
  file:
    path: "/opt/apache/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - conf/sites-available
    - certs
  
- name: Create Openobserve folder
  file:
    path: "/opt/openobserve"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy docker-compatible Apache config
  copy:
    src: httpd.conf
    dest: /opt/apache/conf/httpd.conf

- name: Copy main Apache config
  copy:
    src: apache2.conf
    dest: /opt/apache/conf/apache2.conf

- name: Copy default site config
  copy:
    src: 000-default.conf
    dest: /opt/apache/conf/sites-available/000-default.conf


# Comment these out if not usin TLS, Copy to match your keys, also change in 000-default.conf

- name: Copy certificate
  copy:
    src: yourcert.pem
    dest: /opt/apache/certs/yourcert.pem

- name: Copy key
  copy:
    src: yourcert.pem
    dest: /opt/apache/certs/yourcert.pem

