- name: Copy docker-compose.yml to server
  copy:
    src: docker-compose.yml
    dest: /home/ansible/

- name: Create Apache Docker folders
  file:
    path: "/opt/apache/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - html
    - conf/sites-available
    - certs
    

- name: Copy docker-compatible Apache config
  copy:
    src: httpd.conf
    dest: /opt/apache/conf/httpd.conf

- name: Copy index.html to container web root
  copy:
    src: index.html
    dest: /opt/apache/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: Copy main Apache config
  copy:
    src: apache2.conf
    dest: /opt/apache/conf/apache2.conf

- name: Copy default site config
  copy:
    src: 000-default.conf
    dest: /opt/apache/conf/sites-available/000-default.conf



# Comment these out if not usin TLS, Copy to match your keys, also change in 000-default.conf

- name: Copy certificate
  copy:
    src: turneri.cert.pem
    dest: /opt/apache/certs/turneri.cert.pem

- name: Copy key
  copy:
    src: turneri.key.pem
    dest: /opt/apache/certs/turneri.key.pem

