- name: Install Docker dependencies
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
    state: present
    update_cache: true

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Create directory for Docker GPG keys
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'


- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'


- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=armhf signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: true

- name: Install Docker if missing
  shell: curl -fsSL https://get.docker.com | sh
  when: docker_installed.failed
  
- name: Enable and start Docker
  systemd:
    name: docker
    enabled: true
    state: started