services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD
    command: >
      sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""


  apache:
   image: httpd:2.4-alpine
   ports:
    - 80:80
    - 443:443
   volumes:
    - /opt/apache/conf/:/usr/local/apache2/conf/
    - /opt/apache/conf/sites-available/:/usr/local/apache2/conf/extra/
    - /opt/apache/certs:/usr/local/apache2/conf/certs
    - /opt/apache/html:/usr/local/apache2/htdocs

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    env_file:
    - .env
    environment:
      - REDIS_PASSWORD
      - REDIS_URL


  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8030:80"  # HTTP Port for admin panel access
    env_file:
      - .env    
    environment:
      TZ: 'Europe/Helsinki'
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - /opt/pihole/:/etc/pihole/
    cap_add:
      - SYS_NICE
    restart: unless-stopped



volumes:
  db-data:


### Processor implementation example ###

#  processor:
#    build: /opt/processor
#    container_name: processor
#    restart: unless-stopped
#    
#    depends_on:
#      - db
#      - cache
#    networks:
#      - default
#    ports:
#      - 8000:8000
#    env_file:
#      - .env
#    environment:
#      - REDIS_HOST
#      - REDIS_PASSWORD
#      - REDIS_URL