services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD
    command: >
      sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""


  apache:
   image: httpd:2.4-alpine
   ports:
    - 80:80
    - 443:443
   volumes:
    - /opt/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - /opt/apache/conf/sites-available/000-default.conf:/usr/local/apache2/conf/extra/000-default.conf
    - /opt/apache/certs:/usr/local/apache2/conf/certs
    - /opt/apache/html:/usr/local/apache2/htdocs

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    env_file:
    - .env
    environment:
      - REDIS_PASSWORD
      - REDIS_URL

  processor:
    build: /opt/processor
    container_name: processor
    restart: unless-stopped
    
    depends_on:
      - db
      - cache
    networks:
      - default
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_URL


volumes:
  db-data:
