services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - secrets.env
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    env_file:
    ports:
      - 6379:6379
      - secrets.env
    command: redis-server --requirepass ${REDIS_PASSWORD}


  apache:
   image: httpd:2.4-alpine
   ports:
    - 80:80
    - 443:443

volumes:
  db-data:
