services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    command: sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""


  apache:
   image: httpd:2.4-alpine
   ports:
    - 80:80
    - 443:443
   volumes:
    - /opt/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - /opt/apache/conf/sites-available/000-default.conf:/usr/local/apache2/conf/extra/000-default.conf
    - /opt/apache/certs:/usr/local/apache2/conf/certs
    - /opt/apache/html:/usr/local/apache2/htdocs

#  webapp:
#    build: /opt/webapp
#    container_name: webapp
#    env_file:
#      - ./secrets.env
#    depends_on:
#      - db
#      - cache
#    expose:
#      - "5000"

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@cache:6379

  processor:
    build: /opt/processor
    container_name: processor
    restart: unless-stopped
    
    depends_on:
      - db
      - cache
    networks:
      - default
    ports:
      - 8000:8000

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    networks:
      - default

volumes:
  db-data:
