- name: Create Apache Docker folders
  file:
    path: "/opt/apache/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - html
    - conf/sites-available
    - certs

- name: Copy docker-compatible Apache config
  copy:
    src: httpd.conf
    dest: /opt/apache/conf/httpd.conf

- name: Copy index.html to container web root
  copy:
    src: index.html
    dest: /opt/apache/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: Copy main Apache config
  copy:
    src: apache2.conf
    dest: /opt/apache/conf/apache2.conf

- name: Copy default site config
  copy:
    src: apache/files/000-default.conf
    dest: /opt/apache/conf/sites-available/000-default.conf



# Comment these out if not usin TLS

- name: Copy certificate
  copy:
    src: apache-selfsigned.crt
    dest: /opt/apache/certs/apache-selfsigned.crt

- name: Copy key
  copy:
    src: apache-selfsigned.key
    dest: /opt/apache/certs/apache-selfsigned.key

