- name: Enable module for SSL
  apache2_module:
    state: present
    name: ssl

- name: Enable rewrite module
  apache2_module:
    state: present
    name: rewrite

- name: Enable proxy module
  apache2_module:
    state: present
    name: proxy

- name: Enable proxy_http module
  apache2_module:
    state: present
    name: proxy_http